/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;

  static const _kFontFam2 = 'MyFlutterApp2';
  static const String _kFontPkg2 = null;


  static const _kFontFam3 = 'MyFlutterApp3';
  static const String _kFontPkg3 = null;

  static const _kFontFam4 = 'MyFlutterApp4';
  static const String _kFontPkg4 = null;



  static const IconData postarequest = IconData(0xe800, fontFamily: _kFontFam3, fontPackage: _kFontPkg3);
  static const IconData wallet__2_ = IconData(0xe801, fontFamily: _kFontFam3, fontPackage: _kFontPkg3);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam3, fontPackage: _kFontPkg3);
  static const IconData vector__2_ = IconData(0xe800, fontFamily: _kFontFam2, fontPackage: _kFontPkg2);
  static const IconData bell = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fill_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData edit = IconData(0xe800, fontFamily: _kFontFam4, fontPackage: _kFontPkg4);
  static const IconData filter = IconData(0xe801, fontFamily: _kFontFam4, fontPackage: _kFontPkg4);



}
